version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2020.01
# # Stage 3
  # macos:
  #   macos:
  #     xcode: 11.4

orbs:
  python: circleci/python@0.3.0

jobs:
  test:
    parameters:
      python-version:
        type: string
    executor: linux
# # Stage 3
      # os:
      #   type: executor
    # executor: << parameters.os >>
    steps:
      - checkout
      - python/install:
          tag: << parameters.python-version >>
      - run:
          name: Install coverage
          command: pip install coverage
      - run:
          name: Run tests and collect coverage
          command: coverage run tests.py
      - run:
          name: Upload coverage reports to Codecov
          command: bash <(curl -s https://codecov.io/bash) -F $CIRCLE_JOB
# # Stage 3
          # command: bash <(curl -s https://codecov.io/bash) -F <<parameters.os>>_<< parameters.name >>

workflows:
  all-tests:
    jobs:
      - test:
          name: "test_2_7_18"
          python-version: 2.7.18
      - test:
          name: "test_3_6_10"
          python-version: 3.6.10
      - test:
          name: "test_3_7_7"
          python-version: 3.7.7
      - test:
          name: "test_3_8_3"
          python-version: 3.8.3

# # Stage 2
      # - test:
      #     matrix:
      #       parameters:
      #         python-version: ["10.9.0", "11.9.0", "12.9.1", "13.9.0"]

# # Stage 3
      # - test:
      #     matrix:
      #       parameters:
      #         os: [linux, macos]
      #         python-version: ["10.9.0", "11.9.0", "12.9.1", "13.9.0"]
