version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2020.01
# # Stage 3
#   macos:
#     macos:
#       xcode: 11.4

orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    parameters:
      node-version:
        type: string
    executor: linux
# # Stage 3
    #   os:
    #     type: executor
    # executor: << parameters.os >>

    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests and collect coverage
          command: yarn run test
      - run:
          name: Upload coverage reports to Codecov
          command: bash <(curl -s https://codecov.io/bash) -F $CIRCLE_JOB

workflows:
  all-tests:
    jobs:
      - test:
          node-version: 10.9.0
      - test:
          node-version: 11.9.0
      - test:
          node-version: 12.9.1
      - test:
          node-version: 13.9.0

# # Stage 2
      # - test:
      #     matrix:
      #       parameters:
      #         node-version: ["10.9.0", "11.9.0", "12.9.1", "13.9.0"]

# # Stage 3
      # - test:
      #     matrix:
      #      parameters:
      #        os: [linux, macos]
      #        node-version: ["10.9.0", "11.9.0", "12.9.1", "13.9.0"]
