version: 2.1

executors:
  linux:
    docker:
      - image: cimg/base:2020.01
  macos:
    macos:
      xcode: 11.4

orbs:
  node: circleci/node@3.0.0

jobs:
  test:
    parameters:
      node-version:
        type: string
      os:
        type: executor
    executor: << parameters.os >>
    
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests and collect coverage
          command: |
            if [[ $CIRCLE_JOB = *"macos" ]]; then
              yarn run test-index
            else
              yarn run test
            fi
      - run:
          name: Upload coverage reports to Codecov
          command: |
            if [[ $CIRCLE_JOB = *"macos" ]]; then
              bash <(curl -s https://codecov.io/bash) -F macos
            else
              bash <(curl -s https://codecov.io/bash) -F linux
            fi

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [linux, macos]
              node-version: ["10.9.0", "11.9.0", "12.9.1", "13.9.0"]
